version: 2.1

jobs: # basic units of work in a run
  build:
    docker: # use the Docker executor
      # CircleCI node images available at: https://hub.docker.com/r/circleci/node/
      - image: circleci/node:10.0-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps: # steps that comprise the `build` job
      - checkout 

      - run:
          name: "login"
          command: echo $login
      - run:
          name: "pass"
          command: echo $pass


workflows: # a single workflow with a single job called build
  build:
    jobs:
      - build:
          context: staging
      - build:
          context: beta